<?php
return array(
	array( // row #0
		'id' => 26,
		'dictionary' => 'categories',
		'parentId' => NULL,
		'name' => 'Offero',
	),
	array( // row #1
		'id' => 27,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Motoryzacja',
	),
	array( // row #2
		'id' => 28,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Nieruchomości',
	),
	array( // row #3
		'id' => 29,
		'dictionary' => 'categories',
		'parentId' => 27,
		'name' => 'Samochody',
	),
	array( // row #4
		'id' => 30,
		'dictionary' => 'categories',
		'parentId' => 27,
		'name' => 'Motocykle',
	),
	array( // row #5
		'id' => 35,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Praca',
	),
	array( // row #6
		'id' => 40,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Nieruchomości',
	),
	array( // row #7
		'id' => 41,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Motoryzacja',
	),
	array( // row #8
		'id' => 42,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Łodzie i Pojazdy wodne',
	),
	array( // row #9
		'id' => 43,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Elektronika',
	),
	array( // row #10
		'id' => 44,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Zwierzęta',
	),
	array( // row #11
		'id' => 45,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Dom i Ogród',
	),
	array( // row #12
		'id' => 46,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Antyki i kolekcje',
	),
	array( // row #13
		'id' => 47,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Dla Dziecka',
	),
	array( // row #14
		'id' => 48,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Moda',
	),
	array( // row #15
		'id' => 49,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Zdrowie i Uroda',
	),
	array( // row #16
		'id' => 50,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Sport i Fitness',
	),
	array( // row #17
		'id' => 51,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Muzyka i Rozrywka',
	),
	array( // row #18
		'id' => 52,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Praca',
	),
	array( // row #19
		'id' => 53,
		'dictionary' => 'categories',
		'parentId' => 26,
		'name' => 'Usługi',
	),
	array( // row #20
		'id' => 54,
		'dictionary' => 'categories',
		'parentId' => 40,
		'name' => 'Pokoje do wynajęcia',
	),
	array( // row #21
		'id' => 55,
		'dictionary' => 'categories',
		'parentId' => 40,
		'name' => 'Domy',
	),
	array( // row #22
		'id' => 56,
		'dictionary' => 'categories',
		'parentId' => 40,
		'name' => 'Mieszkania',
	),
	array( // row #23
		'id' => 57,
		'dictionary' => 'categories',
		'parentId' => 40,
		'name' => 'Działki',
	),
	array( // row #24
		'id' => 58,
		'dictionary' => 'categories',
		'parentId' => 40,
		'name' => 'Domki letniskowe',
	),
	array( // row #25
		'id' => 59,
		'dictionary' => 'categories',
		'parentId' => 40,
		'name' => 'Lokale i biura',
	),
	array( // row #26
		'id' => 60,
		'dictionary' => 'categories',
		'parentId' => 40,
		'name' => 'Parkingi i garaże',
	),
	array( // row #27
		'id' => 61,
		'dictionary' => 'categories',
		'parentId' => 41,
		'name' => 'Samochody osobowe',
	),
	array( // row #28
		'id' => 62,
		'dictionary' => 'categories',
		'parentId' => 41,
		'name' => 'Części i akcesoria samochodowe',
	),
	array( // row #29
		'id' => 63,
		'dictionary' => 'categories',
		'parentId' => 41,
		'name' => 'Samochody dostawcze',
	),
	array( // row #30
		'id' => 64,
		'dictionary' => 'categories',
		'parentId' => 41,
		'name' => 'Motocykle i skutery',
	),
	array( // row #31
		'id' => 65,
		'dictionary' => 'categories',
		'parentId' => 41,
		'name' => 'Części i akcesoria do motocykli',
	),
	array( // row #32
		'id' => 66,
		'dictionary' => 'categories',
		'parentId' => 41,
		'name' => 'Ciągniki i maszyny rolnicze',
	),
	array( // row #33
		'id' => 67,
		'dictionary' => 'categories',
		'parentId' => 41,
		'name' => 'Ciężki sprzęt',
	),
	array( // row #34
		'id' => 68,
		'dictionary' => 'categories',
		'parentId' => 41,
		'name' => 'Przyczepy i naczepy',
	),
	array( // row #35
		'id' => 69,
		'dictionary' => 'categories',
		'parentId' => 41,
		'name' => 'Quady, atv i inne',
	),
	array( // row #36
		'id' => 70,
		'dictionary' => 'categories',
		'parentId' => 41,
		'name' => 'Części i akcesoria do innych pojazdów',
	),
	array( // row #37
		'id' => 71,
		'dictionary' => 'categories',
		'parentId' => 42,
		'name' => 'Motorówki',
	),
	array( // row #38
		'id' => 72,
		'dictionary' => 'categories',
		'parentId' => 42,
		'name' => 'Skutery wodne',
	),
	array( // row #39
		'id' => 73,
		'dictionary' => 'categories',
		'parentId' => 42,
		'name' => 'Żaglówki',
	),
	array( // row #40
		'id' => 74,
		'dictionary' => 'categories',
		'parentId' => 42,
		'name' => 'Kajaki i pontony',
	),
	array( // row #41
		'id' => 75,
		'dictionary' => 'categories',
		'parentId' => 42,
		'name' => 'Silniki do łodzi',
	),
	array( // row #42
		'id' => 76,
		'dictionary' => 'categories',
		'parentId' => 42,
		'name' => 'Akcesoria do łodzi',
	),
	array( // row #43
		'id' => 77,
		'dictionary' => 'categories',
		'parentId' => 42,
		'name' => 'Inne pojazdy wodne',
	),
	array( // row #44
		'id' => 78,
		'dictionary' => 'categories',
		'parentId' => 42,
		'name' => 'Łodzie wiosłowe',
	),
	array( // row #45
		'id' => 79,
		'dictionary' => 'categories',
		'parentId' => 43,
		'name' => 'Audio i hi-fi',
	),
	array( // row #46
		'id' => 80,
		'dictionary' => 'categories',
		'parentId' => 43,
		'name' => 'Fotografia i video',
	),
	array( // row #47
		'id' => 81,
		'dictionary' => 'categories',
		'parentId' => 43,
		'name' => 'Gry video i konsole',
	),
	array( // row #48
		'id' => 82,
		'dictionary' => 'categories',
		'parentId' => 43,
		'name' => 'Komputery i software',
	),
	array( // row #49
		'id' => 83,
		'dictionary' => 'categories',
		'parentId' => 43,
		'name' => 'Radiokomunikacja',
	),
	array( // row #50
		'id' => 84,
		'dictionary' => 'categories',
		'parentId' => 43,
		'name' => 'Tablety i bookreadery',
	),
	array( // row #51
		'id' => 85,
		'dictionary' => 'categories',
		'parentId' => 43,
		'name' => 'Telefony i akcesoria',
	),
	array( // row #52
		'id' => 86,
		'dictionary' => 'categories',
		'parentId' => 43,
		'name' => 'Telewizory i odtwarzacze',
	),
	array( // row #53
		'id' => 87,
		'dictionary' => 'categories',
		'parentId' => 43,
		'name' => 'Elektronika inne',
	),
	array( // row #54
		'id' => 88,
		'dictionary' => 'categories',
		'parentId' => 44,
		'name' => 'Akwarystyka',
	),
	array( // row #55
		'id' => 89,
		'dictionary' => 'categories',
		'parentId' => 44,
		'name' => 'Koty',
	),
	array( // row #56
		'id' => 90,
		'dictionary' => 'categories',
		'parentId' => 44,
		'name' => 'Psy',
	),
	array( // row #57
		'id' => 91,
		'dictionary' => 'categories',
		'parentId' => 44,
		'name' => 'Ptaki',
	),
	array( // row #58
		'id' => 92,
		'dictionary' => 'categories',
		'parentId' => 44,
		'name' => 'Inne zwierzęta',
	),
	array( // row #59
		'id' => 93,
		'dictionary' => 'categories',
		'parentId' => 44,
		'name' => 'Zwierzęta gospodarskie',
	),
	array( // row #60
		'id' => 94,
		'dictionary' => 'categories',
		'parentId' => 44,
		'name' => 'Zgubiono lub znaleziono',
	),
	array( // row #61
		'id' => 95,
		'dictionary' => 'categories',
		'parentId' => 44,
		'name' => 'Akcesoria dla zwierząt',
	),
	array( // row #62
		'id' => 96,
		'dictionary' => 'categories',
		'parentId' => 44,
		'name' => 'Usługi dla zwierząt',
	),
	array( // row #63
		'id' => 97,
		'dictionary' => 'categories',
		'parentId' => 45,
		'name' => 'AGD',
	),
	array( // row #64
		'id' => 98,
		'dictionary' => 'categories',
		'parentId' => 45,
		'name' => 'Meble',
	),
	array( // row #65
		'id' => 99,
		'dictionary' => 'categories',
		'parentId' => 45,
		'name' => 'Narzędzia i materiały budowlane',
	),
	array( // row #66
		'id' => 100,
		'dictionary' => 'categories',
		'parentId' => 45,
		'name' => 'Ogród',
	),
	array( // row #67
		'id' => 101,
		'dictionary' => 'categories',
		'parentId' => 45,
		'name' => 'Produkty żywnościowe i napoje',
	),
	array( // row #68
		'id' => 102,
		'dictionary' => 'categories',
		'parentId' => 45,
		'name' => 'Wyposażenie wnętrz',
	),
	array( // row #69
		'id' => 103,
		'dictionary' => 'categories',
		'parentId' => 45,
		'name' => 'Inne do domu i ogrodu',
	),
	array( // row #70
		'id' => 104,
		'dictionary' => 'categories',
		'parentId' => 46,
		'name' => 'Karty kolekcjonerskie',
	),
	array( // row #71
		'id' => 105,
		'dictionary' => 'categories',
		'parentId' => 46,
		'name' => 'Książki i poligrafia',
	),
	array( // row #72
		'id' => 106,
		'dictionary' => 'categories',
		'parentId' => 46,
		'name' => 'Lampy, świeczniki i  lustra',
	),
	array( // row #73
		'id' => 107,
		'dictionary' => 'categories',
		'parentId' => 46,
		'name' => 'Meble zabytkowe',
	),
	array( // row #74
		'id' => 108,
		'dictionary' => 'categories',
		'parentId' => 46,
		'name' => 'Medale i odznaczenia',
	),
	array( // row #75
		'id' => 109,
		'dictionary' => 'categories',
		'parentId' => 46,
		'name' => 'Monety i banknoty',
	),
	array( // row #76
		'id' => 110,
		'dictionary' => 'categories',
		'parentId' => 46,
		'name' => 'Obrazy i rzeźby',
	),
	array( // row #77
		'id' => 111,
		'dictionary' => 'categories',
		'parentId' => 46,
		'name' => 'Rękodzieło',
	),
	array( // row #78
		'id' => 112,
		'dictionary' => 'categories',
		'parentId' => 46,
		'name' => 'Zastawy kuchenne',
	),
	array( // row #79
		'id' => 113,
		'dictionary' => 'categories',
		'parentId' => 46,
		'name' => 'Zabytkowe tekstylia i dekoracje',
	),
	array( // row #80
		'id' => 114,
		'dictionary' => 'categories',
		'parentId' => 46,
		'name' => 'Zegary',
	),
	array( // row #81
		'id' => 115,
		'dictionary' => 'categories',
		'parentId' => 46,
		'name' => 'Znaczki pocztowe',
	),
	array( // row #82
		'id' => 116,
		'dictionary' => 'categories',
		'parentId' => 46,
		'name' => 'Inne kolekcje',
	),
	array( // row #83
		'id' => 117,
		'dictionary' => 'categories',
		'parentId' => 47,
		'name' => 'Artykuły szkolne',
	),
	array( // row #84
		'id' => 118,
		'dictionary' => 'categories',
		'parentId' => 47,
		'name' => 'Bezpieczeństwo i zdrowie dziecka',
	),
	array( // row #85
		'id' => 119,
		'dictionary' => 'categories',
		'parentId' => 47,
		'name' => 'Buty dla dzieci',
	),
	array( // row #86
		'id' => 120,
		'dictionary' => 'categories',
		'parentId' => 47,
		'name' => 'Chrzciny i komunie',
	),
	array( // row #87
		'id' => 121,
		'dictionary' => 'categories',
		'parentId' => 47,
		'name' => 'Ciąża i karmienie',
	),
	array( // row #88
		'id' => 122,
		'dictionary' => 'categories',
		'parentId' => 47,
		'name' => 'Foteliki - nosidełka',
	),
);
