<?php return array (
  'catalog' => 'def',
  'schema' => 'bookshop',
  'name' => 'users',
  'type' => 'BASE TABLE',
  'engine' => 'InnoDB',
  'version' => '10',
  'rowFormat' => 'Compact',
  'rows' => '6',
  'avgRowLength' => '2730',
  'dataLength' => '16384',
  'maxDataLength' => '0',
  'indexLength' => '0',
  'dataFree' => '0',
  'autoIncrement' => '2002',
  'createTime' => '2019-04-18 16:53:54',
  'updateTime' => NULL,
  'checkTime' => NULL,
  'collation' => 'utf8_unicode_ci',
  'checksum' => NULL,
  'createOptions' => '',
  'comment' => '',
);